#ifndef GLOBAL_DEFINITIONS_H
#define GLOBAL_DEFINITIONS_H

#define PROGRAM_NAME "JaG"
//#define CURRENT_VERSION "0.2"

#define JAG_MAJOR_NUMBER 0
#define JAG_MINOR_NUMBER 1
#define JAG_RELEASE_NUMBER 0
#define JAG_BUILD_NUMBER 0


#endif // GLOBAL_DEFINITIONS_H
